apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-sql
  labels:
    app: sql-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sql-test
      pod-label: sql-test-pods
  template:
    metadata:
      labels: 
        app: sql-test
        pod-label: sql-test-pods
    spec:
      containers:
        - name: rest-sql
          image: brianjgrier/simple_rest_sql:latest
          ports:
          - containerPort: 8080
